import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ApiServiceService } from 'src/app/services/api-service.service';
import { AuthInterceptor } from 'src/app/services/auth-interceptor.service';

@Component({
    selector: 'app-client-master',
    templateUrl: './client-master.component.html',
    styleUrls: ['./client-master.component.scss']
})
export class ClientMasterComponent implements OnInit {
    public clientGroup: FormGroup | any;
    authToken = JSON.parse(localStorage.getItem('isLoggedIn') || '')
    clientData: any;
    constructor(public service: ApiServiceService, public auth: AuthInterceptor) { }

    ngOnInit(): void {
        this.clientData = {
            "kycDetail": [
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ClientName": "DEVANG R GANDHI",
                    "ClientPrefix": null,
                    "PanNo": "ALCPG8996N",
                    "PanExempt": "N",
                    "ClientType": "I",
                    "ClientStatus": "02",
                    "FatherOrSpouse": null,
                    "FatherPrefix": null,
                    "FatherName": null,
                    "MotherPrefix": null,
                    "MotherName": null,
                    "Maidenprefix": null,
                    "MaidenName": null,
                    "DOB": "1983-11-16T00:00:00",
                    "Gender": "M",
                    "MaritalStatus": "M",
                    "Citizenship": null,
                    "ResidentialStatus": null,
                    "Occupation": "02",
                    "OccupationOther": null,
                    "IDProof": null,
                    "IDProofRef": null,
                    "IDProofExpiry": null,
                    "Aadhar": "817889426800",
                    "IPVEmployee": null,
                    "IPVDate": null,
                    "PEP": "03",
                    "DOC": null,
                    "IncorporationPlace": null,
                    "CIN": null,
                    "RegistrationNo": null,
                    "RegistrationDate": null,
                    "RegistrationPlace": null,
                    "RegistrationAuthority": null,
                    "AnnualIncome": "02",
                    "AnnualIncomeDate": "2021-02-01T00:00:00",
                    "NetWorth": null,
                    "NetWorthDate": null,
                    "BranchID": "4",
                    "SubBranchID": null,
                    "RMCode": null,
                    "RMName": null,
                    "PayoutFlag": "P",
                    "SettlementDay": 90,
                    "CKYCRefNo": "50067539707865",
                    "KYCMode": "NRML",
                    "CKYCBatchNo": null,
                    "CKYCExportDate": null,
                    "CKYCExportUser": null,
                    "KRAType": null,
                    "KYCBatchNo": null,
                    "KYCExportDate": null,
                    "KYCExportBy": null,
                    "SettlementDate": "2023-04-06T00:00:00",
                    "RiskCategory": "LOW",
                    "RGESSFlag": "N",
                    "TradingSoftwareType": "NONE",
                    "CTCLExport": "N",
                    "BUYBackPosting": "EXP",
                    "FamilyID": null,
                    "OpenDate": "2017-12-22T00:00:00",
                    "CloseDate": null,
                    "CKYCCategory": "01",
                    "TypeOfDoc": "01",
                    "HoldingType": null,
                    "MFClientType": null,
                    "PMS": null,
                    "DivPayMode": null,
                    "CommunicationMode": null,
                    "KYCType": null,
                    "AadharUpdate": null,
                    "MapInID": null,
                    "PaperLessFlag": null,
                    "LEINo": null,
                    "LEIDate": null,
                    "AadharSeededFlag": null,
                    "MFCKYCRefNo": null,
                    "LastModifyBy": null,
                    "LastModifyDate": null,
                    "ZoneID": null,
                    "RegionID": "RGN01"
                }
            ],
            "addDetail": [
                {
                    "AddressID": "AAAR72AAEAABzBQAAI",
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "AddressType": "C",
                    "AddressLine1": "VARDHMAN JASANI PARK STREET NO 3",
                    "AddressLine2": "AIRPORT ROAD",
                    "AddressLine3": "RAIYA ROAD",
                    "AddressCity": "RAJKOT",
                    "AddressPinCode": "360007",
                    "AddressState": "GJ",
                    "AddressCountry": "IN",
                    "AddressPrimary": "Y",
                    "AddressProof": null,
                    "AddressProofOther": null,
                    "AddressProofDate": null,
                    "AddressProofExpiry": null,
                    "AddressProofRef": null,
                    "District": null,
                    "AddressStateOther": null,
                    "AddressProofIssuedBy": null,
                    "Delete": "N"
                }
            ],
            "bankDetail": [
                {
                    "FirmID": "1001",
                    "BankID": "AAAWI3AAEAAB0XFAAj",
                    "ClientCode": "D5422",
                    "PrimaryFlag": "Y",
                    "BankAccountNumber": "01011140004475",
                    "BankAccountType": "S",
                    "BankIFSC": "HDFC0000101",
                    "BankMICR": "360240002",
                    "ChequePrintName": null,
                    "BankCode": "HDFC",
                    "BankName": "HDFC BANK LTD",
                    "BankAddress1": "VENKATESH PLAZADR.  RADHAKRISHNA",
                    "BankAddress2": "ROAD, OPP.  KATHIAWAR",
                    "BankAddress3": "GYMKHANARAJKOTGUJARAT360001",
                    "BankCity": null,
                    "BankPincode": "360001",
                    "BankState": "GJ",
                    "BankSateOther": null,
                    "BankCountry": "IN",
                    "POAFlag": "N",
                    "POADate": null,
                    "Delete": "N",
                    "CustomerID": null,
                    "UMRN": null,
                    "ECSMandateDate": null,
                    "ECSFromDate": null,
                    "ECSToDate": null,
                    "ECSUntilCancel": null,
                    "ECSStatus": null,
                    "ECSFrequency": null,
                    "ECSLimit": null,
                    "AutoDebit": null,
                    "RejectionReason": null,
                    "RBIApprovalNo": null,
                    "PISAccountNo": null,
                    "ACHCustomerID": null,
                    "ActiveFlag": "N",
                    "BankShortCode": "HDFC",
                    "PGCode": "3021",
                    "BankDomain": null,
                    "FundMandate": null
                }
            ],
            "dpDetail": [
                {
                    "SerialNo": "AAAR75AAEAAAlUtABf",
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "DepositoryType": "NSDL",
                    "DepositoryID": "IN301645",
                    "DepositoryName": "GOLDMINE STOCKS PVT LTD",
                    "DepositoryClientID": "10628651",
                    "POAFlag": "Y",
                    "POAID": "00100008",
                    "PrimaryFlag": "Y",
                    "POAActiveDate": "2017-12-30T00:00:00",
                    "POAInactiveDate": null,
                    "POAMarginFlag": "Y",
                    "Delete": "N",
                    "Addendum": "Y",
                    "PledgeAllow": "Y",
                    "Holders": null,
                    "DDPIFlag": null,
                    "DDPIID": null,
                    "DDPIActiveDate": null,
                    "DDPIInactiveDate": null,
                    "Status": "Active",
                    "DDPIORPOAFLAG": "Y"
                }
            ],
            "relatedPersonDetail": [],
            "contactDetail": [
                {
                    "FirmID": "1001",
                    "ContactID": "AAAR74AAEAABz/HAA/",
                    "ClientCode": "D5422",
                    "ContactType": "E",
                    "ISD": null,
                    "STD": null,
                    "ContactNo": null,
                    "ContactEmail": "devanggandhi2000@gmail.com",
                    "PrimaryFlag": "Y",
                    "ActiveFlag": "Y",
                    "InactiveDate": null,
                    "Remark": null,
                    "Delete": "N",
                    "RelatedTo": "S"
                },
                {
                    "FirmID": "1001",
                    "ContactID": "AAAR74AAEAABz/HABA",
                    "ClientCode": "D5422",
                    "ContactType": "M",
                    "ISD": null,
                    "STD": null,
                    "ContactNo": "9824827229",
                    "ContactEmail": null,
                    "PrimaryFlag": "Y",
                    "ActiveFlag": "Y",
                    "InactiveDate": null,
                    "Remark": null,
                    "Delete": "N",
                    "RelatedTo": "S"
                },
                {
                    "FirmID": "1001",
                    "ContactID": "AAAR74AAEAABz/HABB",
                    "ClientCode": "D5422",
                    "ContactType": "P",
                    "ISD": "91",
                    "STD": "0281",
                    "ContactNo": "9824827229",
                    "ContactEmail": null,
                    "PrimaryFlag": "Y",
                    "ActiveFlag": "Y",
                    "InactiveDate": null,
                    "Remark": null,
                    "Delete": "N",
                    "RelatedTo": "S"
                }
            ],
            "nomineeDetail": [
                {
                    "SLNO": "AAASAfAAMAANNTWAAG",
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "NomineeType": "N",
                    "Relation": null,
                    "PreFix": null,
                    "Name": "MONIKA DEVANG GANDHI",
                    "FatherSpouse": null,
                    "FatherPreFix": null,
                    "FatherName": null,
                    "MotherPreFix": null,
                    "MotherName": null,
                    "MaidenPreFix": null,
                    "MaidenName": null,
                    "DOB": null,
                    "PANNO": null,
                    "UID": 999999990276,
                    "Gender": null,
                    "MaritalStatus": null,
                    "ResidentialStatus": null,
                    "Nationnality": null,
                    "Occupation": null,
                    "OccupationOther": null,
                    "IDProof": null,
                    "IDProofRefNo": null,
                    "Address1": "JASANI PARK",
                    "Address2": "VASUNDHARA PARK",
                    "Address3": "AIRPORT ROAD",
                    "City": "RAJKOT",
                    "Pincode": "360007",
                    "District": null,
                    "State": "GJ",
                    "StateOther": null,
                    "Country": "IN",
                    "AddressProof": null,
                    "AddressProofOther": null,
                    "AddressProofRef": null,
                    "AddressProofDate": null,
                    "AddressProofDateExpiry": null,
                    "Delete": "N",
                    "SharePercentage": 100,
                    "EmailID": "devanggandhi2000@gmail.com",
                    "ISD": null,
                    "Mobile": "9824827229",
                    "MinorInd": "N",
                    "NomineeSerialNo": "1",
                    "NomineeStatusCheck": "Y"
                }
            ],
            "brokMapping": [
                {
                    "FirmID": "1001",
                    "ExchangeID": "ALL",
                    "SegmentID": "CAP",
                    "SlabID": "CAP-00410",
                    "AccountID": "D5422",
                    "StartDate": "2017-12-23T00:00:00",
                    "UpToDec": 2,
                    "RoundTruncFlag": "U",
                    "OptionBrokMethod": "P",
                    "UpdateBy": "administrator",
                    "UpdateDate": "2020-08-14T10:49:33",
                    "SellSlabID": null
                }
            ],
            "exchangeDetail": [
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "CategoryCode": "1",
                    "CategoryName": "INDIVIDUAL / PROPRIETORSHIP FIRMS",
                    "UCC": "D5422",
                    "ActiveFlag": "Y"
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "BSE",
                    "ExchangeName": "BOMBAY STOCK EXCHANGE LTD",
                    "CategoryCode": "I",
                    "CategoryName": "INDIVIDUALS",
                    "UCC": "D5422",
                    "ActiveFlag": "Y"
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "MCX",
                    "ExchangeName": "MULTI COMMODITY EXCHANGE OF INDIA LTD",
                    "CategoryCode": null,
                    "CategoryName": null,
                    "UCC": null,
                    "ActiveFlag": "N"
                }
            ],
            "segmentDetail": [
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "BSE",
                    "ExchangeName": "BOMBAY STOCK EXCHANGE LTD",
                    "SegmentID": "CAP",
                    "SegmentName": "Capital Market",
                    "ActiveDate": "2017-12-22T00:00:00",
                    "InactiveDate": null,
                    "TradingAllow": "Y",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "BSE",
                    "ExchangeName": "BOMBAY STOCK EXCHANGE LTD",
                    "SegmentID": "COM",
                    "SegmentName": "Commodity Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "BSE",
                    "ExchangeName": "BOMBAY STOCK EXCHANGE LTD",
                    "SegmentID": "FNO",
                    "SegmentName": "Capital Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "MCX",
                    "ExchangeName": "MULTI COMMODITY EXCHANGE OF INDIA LTD",
                    "SegmentID": "COM",
                    "SegmentName": "Commodity Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "SegmentID": "CAP",
                    "SegmentName": "Capital Market",
                    "ActiveDate": "2017-12-22T00:00:00",
                    "InactiveDate": null,
                    "TradingAllow": "Y",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "SegmentID": "COM",
                    "SegmentName": "Commodity Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "SegmentID": "CUR",
                    "SegmentName": "Currency Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "SegmentID": "FNO",
                    "SegmentName": "Capital Derivative",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                },
                {
                    "FirmID": "1001",
                    "ClientCode": "D5422",
                    "ExchangeID": "NSE",
                    "ExchangeName": "NATIONAL STOCK EXCHANGE LTD",
                    "SegmentID": "SLB",
                    "SegmentName": "Security Lending and Borrowing",
                    "ActiveDate": null,
                    "InactiveDate": null,
                    "TradingAllow": "N",
                    "Remarks": null,
                    "CPCode": null,
                    "CMID": null,
                    "UCCExported": "N",
                    "UCCExportDate": null,
                    "UCCExportBy": null,
                    "UCCSuccess": "N",
                    "UCCClassification": null,
                    "ExchangeVerification": null,
                    "CPCodePledge": null
                }
            ],
            "customDetail": [],
            "backofficeDetail": [
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "ProtectedAccount": "N",
                    "ModifyRemark": null,
                    "UIDEnrollmentNo": null,
                    "PayoutFlag": "P",
                    "SettlementDay": 90,
                    "CKYCRefNo": "50067539707865",
                    "KYCMode": "NRML",
                    "CKYCBatchNo": null,
                    "CKYCExportDate": null,
                    "CKYCExportUser": null,
                    "KRAType": null,
                    "KYCBatchNo": null,
                    "KYCExportDate": null,
                    "KYCExportBy": null,
                    "SettlementDate": "2023-04-06T00:00:00",
                    "RiskCategory": "LOW",
                    "RGESSFlag": "N",
                    "TradingSoftwareType": "NONE",
                    "CTCLExport": "N",
                    "BuyBackPosting": "EXP",
                    "KYCReferenceNo": null,
                    "PaymentType": "ONPAYOUT",
                    "CTCLCategory": null,
                    "GSTRegistrationNo": null,
                    "GSTRegistrationDate": "1900-01-01T00:00:00",
                    "AadharVirtualID": null,
                    "UPIID": null,
                    "FATCAFlag": "Y",
                    "MinorFlag": "N",
                    "MTFStatus": "N",
                    "MTFStatusDate": null,
                    "MTFRemarks": null,
                    "ModifiedBy": null,
                    "ModifiedDate": null,
                    "DormateRemark": "DORMAT",
                    "DormateUpdateBy": "em0028",
                    "DormateUpdateDate": "2022-10-15T15:36:26",
                    "ClientShare": null,
                    "Status": "02",
                    "StatusDesc": "Inactive",
                    "CSC": "N",
                    "APPANNo": null,
                    "NomineeOptFlag": "Y",
                    "UnTracedFlag": "N",
                    "EducationCode": null,
                    "OtherMktExperience": null,
                    "StockMktExperience": null,
                    "DerivativeMktExperience": null,
                    "LanguageCode": null,
                    "FATCACountry": null,
                    "FATCATin": null,
                    "FATCADate": null,
                    "LastTradeDate": "2021-10-14T00:00:00",
                    "CVLKRAStatus": null
                }
            ],
            "documentDetail": [
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "PAN",
                    "DocumentName": "PAN Card",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "PHOTO",
                    "DocumentName": "Photograph",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "UID",
                    "DocumentName": "Aadhar Card",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "PASSPORT",
                    "DocumentName": "Passport",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "DL",
                    "DocumentName": "Driving Licence",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "VOTERID",
                    "DocumentName": "Voter ID Card",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "NAREGA",
                    "DocumentName": "NREGA Job Card",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "SIGN",
                    "DocumentName": "Signature",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "BANK",
                    "DocumentName": "Bank Statement/Passbook",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "BILLS",
                    "DocumentName": "Utility Bill(Gas,Telephone,Postpaid Mobile) ",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "OTHER",
                    "DocumentName": "Others",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "KYCFORM",
                    "DocumentName": "KYC Form",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "ACOPEN",
                    "DocumentName": "Account Opening Form",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "OVD",
                    "DocumentName": "Officially valid document(s) in respect of person authorized to transact",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "COI",
                    "DocumentName": "Certificate of Incorporation/Formation",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "RC",
                    "DocumentName": "Registration Certificate",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "MAA",
                    "DocumentName": "Memorandum and Articles of Association",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "PD",
                    "DocumentName": "Partnership Deed",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "TD",
                    "DocumentName": "Trust Deed",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "RB",
                    "DocumentName": "Resolution of Board/ Managing Committee",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "POA",
                    "DocumentName": "Power of Attorney granted to its manager, officers or employees to transact on its behalf",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "AP1",
                    "DocumentName": "Activity Proof – 1",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                },
                {
                    "FirmID": "1001",
                    "AccountID": "D5422",
                    "DocumentID": "AP2",
                    "DocumentName": "Activity Proof – 2",
                    "DocumentFileName": null,
                    "Remarks": null,
                    "DataAvilable": "N",
                    "DocData": null
                }
            ],
            "OtherHolderDetail": [],
            "CustodianDetail": []
        }

        this.clientGroup = new FormGroup({
            ClientCode: new FormControl("", Validators.required),
        });
    }

    get f() {
        return this.clientGroup.controls;
    }

    public save() {
        if (this.clientGroup.valid) {
            this.service.getClientMasterDetail(this.clientGroup.value).subscribe((res: any) => {
                console.log("res", res)
            }, (err: any) => {
                console.log("err", err)
            })
        }
        console.log(this.clientGroup);
    }

}
